Improvements to error reporting in caldp.process and caldp-process to better   utilize program exit status, most critically to characterize Astrodrizzle   memory errors with exit status visible in the batch failure events. Added exit_codes.py file to be shared-with/copied-to CALCLOUD verbatim. Added exit handling functions and context managers,  with doctests,  to make   exit handling code cleaner, standard, and more succinct.  sysexit module. Added caldp-ecr-login <admin_role> script to make it simpler to login to   the ECR repository. Added tox.ini to facilitate command line flake8, black, and bandit tests. Added exit error simulation via CALDP_SIMULATE_ERROR env var which   can be defined to values in exit_codes.py to simulate exceptions/exits. Added default for CRDS_READONLY_CACHE in caldp-docker-run-container Work on error codes, added text explanations for CALDP numerical codes   returned to CALCLOUD. Removed submit-ipppssoot message,  adjusted messages.py and test_all.py Modified tests for Messages.start_message -> Messages.init Turned off -x in caldp-docker-run-container Added caldp-image-sh to run bash in an interactive CALDP container. Added "log linux memory limit" to sysexit.exit_reciever,  typically first   messaage seen in processing.

diff --git a/scripts/caldp-process b/scripts/caldp-process
--- a/scripts/caldp-process
+++ b/scripts/caldp-process
@@ -72,7 +72,6 @@ if [ $output_path != "none" -a $output_location == 's3' ]; then
     fi
 fi
 
-
 echo ........................................ processing log ..............................................
 pwd
 set -o pipefail && $TIME --verbose -o process_metrics.txt \
@@ -83,9 +82,6 @@ echo "Processing exit status ${process_exit_status}"
 
 processing_output_dir=`caldp-get-output-path  $output_path $ipppssoot`
 echo "Processing output_dir is" $processing_output_dir
-
-# logs_output_dir="${processing_output_dir}/logs"
-# echo "Logs output_dir is" $logs_output_dir
 
 previews_output_dir="${processing_output_dir}/previews"
 echo "Previews output_dir is" $previews_output_dir
@@ -111,5 +107,30 @@ echo ........................... handling outputs for ${output_location} .......
 
 # Note: this action is not logged since log files are being transferred.
 python -m caldp.messages $input_path $output_path $ipppssoot
+messages_exit_status=$?
+echo "messages exit status = ${messages_exit_status}"
 
-[[ $process_exit_status -eq 0 && $preview_exit_status -eq 0 ]] || exit 1
+# This is iffy:  only report MemoryError if the program returns non-zero status.  Otherwise assume it dealt with it.
+if [[ $process_exit_status -ne 0 ]]; then
+    grep MemoryError process.txt
+    if [[ $? -eq 0 ]]; then
+        echo "MemoryError found in process.txt;  exiting with status 31,  SUBPROCESS_MEMORY_ERROR"
+        exit 31
+    else
+        echo "Exiting with processing status ${process_exit_status}"
+        exit $process_exit_status
+    fi
+fi
+
+if [[ $preview_exit_status -ne 0 ]]; then
+    echo "Exiting with preview status ${preview_exit_status}"
+    exit $preview_exit_status
+fi
+
+if [[ $messages_exit_status -ne 0 ]]; then
+    echo "Exiting with message status ${messages_exit_status}"
+    exit $preview_exit_status
+fi
+
+echo "Exiting normally, status 0"
+exit 0
